[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/time" = "@stdlib.time.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "crypto"
    version = "@project.version@"
    path = "../crypto-native/build/libs/crypto-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["crypto"]
